apiVersion: v1
kind: Pod
metadata:
  name: api-db
  labels:
    name: api-db
spec:
  containers:
  - name: api-db
    image: postgres:13.2
    imagePullPolicy: IfNotPresent
    ports:
    - name: api-db
      containerPort: 5433
    env:
    - name: POSTGRES_DB
      value: api-db
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    volumeMounts:
    - name: api-db-data
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: api-db-data
    hostPath:
      path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: api-db
spec:
  selector:
    app: api-db
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432
--- 