apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-db-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-api-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-db-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-db
  template:
    metadata:
      labels:
        app: api-db
    spec:
      volumes:
        - name: api-db-pv-storage
          persistentVolumeClaim:
            claimName: api-db-pv-claim
      containers:
        - name: api-db
          image: postgres:13.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5433
          env:
            - name: POSTGRES_DB
              value: api-db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: api-db-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: api-db
  labels:
    app: api-db
spec:
  type: NodePort
  ports:
    - port: 5433
      targetPort: 5432
  selector:
    app: api-db